run:
  # timeout for analysis
  timeout: 5m

linters:
  # Enable specific linters
  enable:
    - errcheck     # Checks for unchecked errors
    - gofmt        # Checks code formatting
    - gosimple     # Simplifies code
    - govet        # Finds potential issues
    - ineffassign  # Detects ineffective assignments
    - staticcheck  # Advanced static analysis
    - typecheck    # Type checking
    - unused       # Finds unused code
    - gocritic     # Provides additional code recommendations
    - goimports    # Manages import statements

  # Disable some default linters
  disable:
    - depguard
    - gosec
    - nolintlint

linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  
  gofmt:
    # simplify code: gofmt with `-s` option
    simplify: true
  
  gomnd:
    # don't include magic numbers in checks
    ignored-numbers:
      - '3000'  # server port number
    
  gocritic:
    enabled-checks:
      - commentedOutCode
      - deprecatedComment
      - dupImport
      - ifElseChain
      - regexpMust

issues:
  # Excluding configuration
  exclude-rules:
    # Exclude some linters for test files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  # Maximum issues per linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3

# Optional: Performance optimizations
performance:
  # Skip directories
  skip-dirs:
    - vendor
    - third_party
    - testdata